name: linux-clang

on:
  push:
    branches:
      - 'master'

jobs:
  linux-clang:
    name: "linux-clang"
    runs-on: ubuntu-latest
    env:
      CC:   clang
      CXX:  clang++
    
    steps:
    - uses: actions/checkout@v1

    - name: setup
      run: sudo apt-get install -y llvm-10 clang-10
    - name: configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ../
    - name: build
      run: |
        cd build
        make
    - name: run_tests
      run: |
        ./build/zippptests